# Generated by Django 4.1 on 2023-01-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldOne', models.CharField(max_length=50)),
                ('fieldTwo', models.CharField(max_length=50)),
            ],
        ),
    ]
