# Generated by Django 4.1.6 on 2023-02-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('admintion_date', models.DateTimeField(max_length=50, verbose_name='DateTime')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('1', 'زن'), ('2', 'مرد'), ('3', 'باردار')], max_length=50, verbose_name='gender')),
                ('transportion', models.CharField(choices=[('1', 'آمبولانس خصوصی 115'), ('2', ' آمبولانس خصوصی'), ('3', 'وسیله شخصی'), ('3', 'امداد هوایی')], max_length=50, verbose_name='gender')),
                ('other', models.CharField(blank=True, max_length=200, verbose_name='other')),
                ('visit_last24hour', models.CharField(blank=True, max_length=200, verbose_name='privious_visit')),
                ('pationt_main_complaint', models.CharField(max_length=1000, verbose_name='pationt_main_complaint')),
                ('Alergics', models.CharField(max_length=1000, verbose_name='Alergics')),
                ('level_of_consciousness', models.CharField(choices=[('1', 'A'), ('1', 'V'), ('1', 'P'), ('1', 'U')], max_length=200, verbose_name='level_of_consciousness')),
                ('Airway_hazard', models.CharField(choices=[('1', 'دیسترس تنفسی'), ('1', 'سیانوز'), ('1', 'علایم شوک'), ('1', 'Spo2<90')], max_length=200, verbose_name='مخاطره راه هوایی')),
                ('Lethargy_and_sleepiness', models.BooleanField()),
                ('Pain_with_severe_distress', models.BooleanField()),
                ('medical_record', models.CharField(max_length=200, verbose_name='medical_record')),
                ('medication_history', models.CharField(max_length=200, verbose_name='medication_history')),
                ('vital_Signs2_BP', models.CharField(max_length=200, verbose_name='vital_Signs2_BP')),
                ('vital_Signs2_RP', models.CharField(max_length=200, verbose_name='vital_Signs2_RP')),
                ('vital_Signs2_RR', models.CharField(max_length=200, verbose_name='vital_Signs2_RR')),
                ('vital_Signs2_T', models.CharField(max_length=200, verbose_name='vital_Signs2_T')),
                ('vital_Signs2_Spo2', models.CharField(max_length=200, verbose_name='vital_Signs2_Spo2')),
                ('Facilities', models.BooleanField(verbose_name='تعداد تسهیلات مورد نظر بیمار اورژانس')),
                ('vital_Signs3_BP', models.CharField(max_length=200, verbose_name='vital_Signs3_BP')),
                ('vital_Signs3_RP', models.CharField(max_length=200, verbose_name='vital_Signs3_RP')),
                ('vital_Signs3_RR', models.CharField(max_length=200, verbose_name='vital_Signs3_RR')),
                ('vital_Signs3_T', models.CharField(max_length=200, verbose_name='vital_Signs3_T')),
                ('vital_Signs3_Spo2', models.CharField(max_length=200, verbose_name='vital_Signs3_Spo2')),
                ('faculties', models.CharField(choices=[('1', 'یک مورد'), ('2', 'هیچ')], max_length=10)),
                ('level_of_triage', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('emergency_department', models.CharField(max_length=75)),
                ('referal_time', models.DateTimeField()),
                ('triage_nurse_name', models.CharField(max_length=50)),
                ('doctor_inst', models.CharField(max_length=1000)),
                ('doctor_examination_time', models.DateTimeField()),
                ('doctor_name', models.CharField(max_length=50)),
                ('nurse_report', models.CharField(max_length=1000)),
                ('report_time', models.DateTimeField()),
                ('nurse_name', models.CharField(max_length=50)),
                ('transfer_date', models.DateField()),
                ('transfer_time', models.TimeField()),
                ('released', models.BooleanField()),
                ('transfered_to_department', models.CharField(max_length=75, null=True)),
                ('transfered_to_hospital', models.CharField(max_length=75, null=True)),
                ('surgery_relationship', models.CharField(max_length=50)),
                ('surgery_city', models.CharField(max_length=50)),
                ('surgery_hospital_name', models.CharField(max_length=75)),
                ('surgery_witness_one', models.CharField(max_length=50)),
                ('surgery_witness_two', models.CharField(max_length=50)),
                ('surgery_Date', models.DateField(max_length=50)),
                ('consentualRelease_patient', models.CharField(max_length=50)),
                ('consentualRelease_patientFamily', models.CharField(max_length=50)),
                ('consentualRelease_witness_one', models.CharField(max_length=50)),
                ('consentualRelease_witness_two', models.CharField(max_length=50)),
                ('consentualRelease_Date', models.DateField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TriageTest',
        ),
    ]
